apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: accord
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.template.yaml
  - postgres.yaml
  - redis.yaml
  - backend.yaml
  - celery-worker.yaml
  - frontend.yaml
